from enum import Enum


class SystemRole(str, Enum):
    ADMINISTRATOR = "administrator"
    FACULTY = "faculty"
    PROJECT_MANAGER = "project_manager"
    TEAM_LEAD = "team_lead"
    DEVELOPER = "developer"
    QA_ENGINEER = "qa_engineer"
    STAKEHOLDER = "stakeholder"
    VIEWER = "viewer"


SYSTEM_ROLES: dict[str, dict] = {
    SystemRole.ADMINISTRATOR: {
        "name": "Administrator",
        "description": "Full system access. Manages users, organizations, system settings, and has unrestricted access to all resources.",
        "hierarchy_level": 0,
    },
    SystemRole.FACULTY: {
        "name": "Faculty",
        "description": "Academic oversight role. Can view and approve projects, access reports, and monitor student team progress.",
        "hierarchy_level": 1,
    },
    SystemRole.PROJECT_MANAGER: {
        "name": "Project Manager",
        "description": "Full project lifecycle management. Creates projects, manages teams, assigns tasks, schedules meetings, and generates reports.",
        "hierarchy_level": 2,
    },
    SystemRole.TEAM_LEAD: {
        "name": "Team Lead",
        "description": "Leads a team within a project. Manages team members, assigns tasks, conducts code reviews, and reports to the project manager.",
        "hierarchy_level": 3,
    },
    SystemRole.DEVELOPER: {
        "name": "Developer",
        "description": "Core contributor. Creates and updates tasks, logs work, submits deliverables, and participates in meetings.",
        "hierarchy_level": 4,
    },
    SystemRole.QA_ENGINEER: {
        "name": "QA Engineer",
        "description": "Quality assurance specialist. Creates and manages test cases, reports bugs, verifies fixes, and tracks quality metrics.",
        "hierarchy_level": 5,
    },
    SystemRole.STAKEHOLDER: {
        "name": "Stakeholder",
        "description": "External or internal stakeholder. Views project progress, provides feedback, and accesses published reports.",
        "hierarchy_level": 6,
    },
    SystemRole.VIEWER: {
        "name": "Viewer",
        "description": "Read-only access. Can view projects, tasks, and reports but cannot modify any resources.",
        "hierarchy_level": 7,
    },
}
PERMISSION_DEFINITIONS: list[dict[str, str]] = [
    {"codename": "project.view", "name": "View Projects", "category": "project"},
    {"codename": "project.create", "name": "Create Projects", "category": "project"},
    {"codename": "project.update", "name": "Update Projects", "category": "project"},
    {"codename": "project.delete", "name": "Delete Projects", "category": "project"},
    {
        "codename": "project.manage_settings",
        "name": "Manage Project Settings",
        "category": "project",
    },
    {"codename": "task.view", "name": "View Tasks", "category": "task"},
    {"codename": "task.create", "name": "Create Tasks", "category": "task"},
    {"codename": "task.update", "name": "Update Tasks", "category": "task"},
    {"codename": "task.delete", "name": "Delete Tasks", "category": "task"},
    {"codename": "task.assign", "name": "Assign Tasks", "category": "task"},
    {
        "codename": "task.change_status",
        "name": "Change Task Status",
        "category": "task",
    },
    {"codename": "team.view", "name": "View Teams", "category": "team"},
    {"codename": "team.create", "name": "Create Teams", "category": "team"},
    {"codename": "team.update", "name": "Update Teams", "category": "team"},
    {"codename": "team.delete", "name": "Delete Teams", "category": "team"},
    {
        "codename": "team.manage_members",
        "name": "Manage Team Members",
        "category": "team",
    },
    {"codename": "meeting.view", "name": "View Meetings", "category": "meeting"},
    {"codename": "meeting.create", "name": "Create Meetings", "category": "meeting"},
    {"codename": "meeting.update", "name": "Update Meetings", "category": "meeting"},
    {"codename": "meeting.delete", "name": "Delete Meetings", "category": "meeting"},
    {"codename": "report.view", "name": "View Reports", "category": "report"},
    {"codename": "report.create", "name": "Create Reports", "category": "report"},
    {"codename": "report.update", "name": "Update Reports", "category": "report"},
    {"codename": "report.delete", "name": "Delete Reports", "category": "report"},
    {"codename": "report.export", "name": "Export Reports", "category": "report"},
    {"codename": "user.view", "name": "View Users", "category": "user"},
    {"codename": "user.create", "name": "Create Users", "category": "user"},
    {"codename": "user.update", "name": "Update Users", "category": "user"},
    {"codename": "user.delete", "name": "Delete Users", "category": "user"},
    {"codename": "user.manage_roles", "name": "Manage User Roles", "category": "user"},
    {
        "codename": "organization.view",
        "name": "View Organizations",
        "category": "organization",
    },
    {
        "codename": "organization.create",
        "name": "Create Organizations",
        "category": "organization",
    },
    {
        "codename": "organization.update",
        "name": "Update Organizations",
        "category": "organization",
    },
    {
        "codename": "organization.delete",
        "name": "Delete Organizations",
        "category": "organization",
    },
    {
        "codename": "notification.view",
        "name": "View Notifications",
        "category": "notification",
    },
    {
        "codename": "notification.manage",
        "name": "Manage Notifications",
        "category": "notification",
    },
    {"codename": "audit.view", "name": "View Audit Logs", "category": "audit"},
]
ALL_PERMISSION_CODENAMES: set[str] = {p["codename"] for p in PERMISSION_DEFINITIONS}
DEFAULT_PERMISSIONS: dict[str, list[str]] = {
    SystemRole.ADMINISTRATOR: list(ALL_PERMISSION_CODENAMES),
    SystemRole.FACULTY: [
        "project.view",
        "project.create",
        "project.update",
        "task.view",
        "team.view",
        "meeting.view",
        "report.view",
        "report.create",
        "report.export",
        "user.view",
        "organization.view",
        "notification.view",
        "audit.view",
    ],
    SystemRole.PROJECT_MANAGER: [
        "project.view",
        "project.create",
        "project.update",
        "project.manage_settings",
        "task.view",
        "task.create",
        "task.update",
        "task.delete",
        "task.assign",
        "task.change_status",
        "team.view",
        "team.create",
        "team.update",
        "team.manage_members",
        "meeting.view",
        "meeting.create",
        "meeting.update",
        "meeting.delete",
        "report.view",
        "report.create",
        "report.update",
        "report.export",
        "user.view",
        "notification.view",
        "notification.manage",
    ],
    SystemRole.TEAM_LEAD: [
        "project.view",
        "task.view",
        "task.create",
        "task.update",
        "task.assign",
        "task.change_status",
        "team.view",
        "team.update",
        "team.manage_members",
        "meeting.view",
        "meeting.create",
        "meeting.update",
        "report.view",
        "report.create",
        "user.view",
        "notification.view",
    ],
    SystemRole.DEVELOPER: [
        "project.view",
        "task.view",
        "task.create",
        "task.update",
        "task.change_status",
        "team.view",
        "meeting.view",
        "report.view",
        "notification.view",
    ],
    SystemRole.QA_ENGINEER: [
        "project.view",
        "task.view",
        "task.create",
        "task.update",
        "task.change_status",
        "team.view",
        "meeting.view",
        "report.view",
        "notification.view",
    ],
    SystemRole.STAKEHOLDER: [
        "project.view",
        "task.view",
        "team.view",
        "meeting.view",
        "report.view",
        "report.export",
        "notification.view",
    ],
    SystemRole.VIEWER: [
        "project.view",
        "task.view",
        "team.view",
        "meeting.view",
        "report.view",
        "notification.view",
    ],
}
